Backend
CatalinB7/dogs-labeling pull request #2
Opened 2021-07-16 14:12 UTC by CatalinB7

There are 2 directories, backend and frontend, but also 3 older files inside dogs_labeling directory that should have been removed.

2021-07-16 17:30 UTC, CalinaCristian requested changes
Good job with this project! I've looked through the code, and I've left some suggestions, and I'd also add some keynotes here:

👍  I like the decoupling of backend and frontend and the usage of webpack to bundle files & dev server !
👍  I also liked that you documented the functions (at least on backend)
👍  I really like the backend code structure, it is very easy to follow !

👎  The page doesn't seem to be responsive (except for the usage of flex)
👎  You don't seem to use routings, which was one of the requirements, and you use some h1 query weird logic to determine on which page you are on (also you should be able to go to all the rouites, including the user selection..so maybe add a logout button?)
👎 The FE code still seems a bit cluttered, and you keep a lot of logic on FE instead of relying on the BE to give you the actual data. If there will ever be a requirement
to have multiple users with access to the same adorable/silly lists, there will need to be a lot of changes to the code.

2021-07-16 17:30 UTC, CalinaCristian commented on dogs_labeling/frontend/src/picsManipulation.ts
> +        let text = document.querySelector("h1").innerHTML;
Why do you need to check this stuff since you can have multiple h1's in the application. You should have (query param) routes as it was a requirement, and use that to determine on which of the pages you are on.
Also, since this logic is repeated, maybe make a function that determines on which view/route you are on.

2021-07-16 17:30 UTC, CalinaCristian commented on dogs_labeling/frontend/src/picsManipulation.ts
> +        if (alreadySent[text][idx]) {
Also, it's a pretty bad practice to keep the state of pictures that are already sent to the backend on the frontend code. The backend should be the source of truth (if you ever want to persist the session and the already loaded pics on refresh instead of requesting new random ones, this logic of yours would not work).

2021-07-16 17:30 UTC, CalinaCristian commented on dogs_labeling/frontend/src/picsManipulation.ts
> +        setReceivedLinks(getReceivedLinks().filter(elem => elem != link));
this is still optimistic ui, you don't call the endpoint do validate that the resource was actually deleted. You should call the get again here, and update the view based on what the actual data is in the backend.

2021-07-16 17:30 UTC, CalinaCristian commented on dogs_labeling/index.html
> +<script src="./script.js"></script>
Remove this outdatred file.

2021-07-16 17:30 UTC, CalinaCristian commented on dogs_labeling/script.js
> +const noPics = 8;
isn't this file outdated? Shouldn't this be removed?

2021-07-16 17:30 UTC, CalinaCristian commented on dogs_labeling/frontend/index.html
> +    <script src="./dist/bundle.js"></script>
I don't like the position of the script here, you should put it in the head, and use [async/defer](https://www.digitalocean.com/community/tutorials/html-defer-async) attribute

2021-07-16 17:30 UTC, CalinaCristian commented on dogs_labeling/frontend/src/script.ts
> +});
why don't you use the onclick binding directly on the buttons?

2021-07-16 17:30 UTC, CalinaCristian commented on dogs_labeling/frontend/src/script.ts
> +    event.preventDefault();
what event? you don't use it as parameter.

2021-07-16 17:30 UTC, CalinaCristian commented on dogs_labeling/frontend/src/script.ts
> +function makeElementsVisible(response: myResponse, text: string) {
this function seems a bit too complex and hard to follow, maybe you should refactor a bit the cards creation so this wouldn't be so complicated.

2021-07-16 17:58 UTC, alexdudescu reviewed
I really like the frontend dev setup with webpack. 

Also I'm in alignment with what Cristi mentioned. The logic on the fe side also feels a bit "backend-esque". You could probably take advantage more of language features such as the forEach, map, reduce functions that would make your code cleaner. 

Overall nice project! ♥

2021-07-16 17:58 UTC, alexdudescu commented on dogs_labeling/frontend/package.json
> +  }
When installing a package using npm you would use `npm i awesome-package` and that will add it to the dependencies but you can also add the `-D` or `--save-dev` flag and that will add it to the dev dependencies. When adding a new package to your project you should ask yourself if it's something you need for development only like the typescript compiler, typescript's @type packages or webpack, or if it's something that provides functionality for the consumer of your project and should end up in the actual build like a component library, lodash, etc.

2021-07-16 17:58 UTC, alexdudescu commented on dogs_labeling/frontend/src/httpServices.ts
> +    let response = await fetch('http://localhost:8080/preferences', {
```suggestion
    const baseUrl = 'http://localhost:8080/preferences';
    let response = await fetch(baseUrl, {
```

If for example the port your app is running on changes then you would have to go through all the instances where you use the hardcoded url and change it. In general, when you're using a value multiple times, think if would be useful to extract it as a const.

2021-07-16 22:46 UTC, CalinaCristian commented on dogs_labeling/frontend/package.json
> +  }
i like how you tagged @type which is an actual github account

2021-07-21 14:30 UTC, CatalinB7 commented on dogs_labeling/frontend/src/script.ts
> +});
like this?
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-3cb787b8ed440dcf7e44c103d614a482c34866350f31e8b770afc564cab9225cR31-R34

2021-07-21 14:32 UTC, CatalinB7 commented on dogs_labeling/frontend/src/script.ts
> +    event.preventDefault();
passed event as parameter now
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-3cb787b8ed440dcf7e44c103d614a482c34866350f31e8b770afc564cab9225cR36-R38

2021-07-21 14:36 UTC, CatalinB7 commented on dogs_labeling/frontend/package.json
> +  }
moved most of the dependencies to devDependencies
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-e575b5aad16756346f1e1ab58b0aa1d67c54b09fefcf17c575ce413776dd7f40R1-R22

2021-07-21 14:38 UTC, CatalinB7 commented on dogs_labeling/frontend/src/httpServices.ts
> +    let response = await fetch('http://localhost:8080/preferences', {
followed your advice and i also created a generic fetch function
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-b0abc765a3b7c7158a09dc4d11771c0cc58bf9a6d6f158c2791d2ad656fbb37fR4-R19

2021-07-21 14:42 UTC, CatalinB7 commented on dogs_labeling/backend/src/db.ts
> +type Dict = { [key in Category]: string[] };
```type categoriesToLinks = { [key in Category]: string[] };```

2021-07-21 14:44 UTC, CatalinB7 commented on dogs_labeling/frontend/src/styles.css
> +    animation: rotation 3s;
on hover changing only color
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-86bd6ef696b30ab1e82966387c57901d489f42614d8fa8f4797095050f58a6edR148-R151

2021-07-21 14:46 UTC, CatalinB7 commented on dogs_labeling/frontend/src/appState.ts
> +//probably i should manage the state in another way
done as suggested
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-d9270f86a9087ab9516b7bc6abf59f12e83ef38e8899500a06fb41f48b68d173R22-R113

2021-07-21 14:49 UTC, CatalinB7 commented on dogs_labeling/frontend/src/picsManipulation.ts
> +        setReceivedLinks(getReceivedLinks().filter(elem => elem != link));
less optimistic more realistic :D
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-5835e833b0368ccea5f129aae6a43784e4c574154f58b8b560bd84d3ceb26ccaR33-R37

2021-07-21 14:51 UTC, CatalinB7 commented on dogs_labeling/frontend/src/httpServices.ts
> +//receive parameters for method and url maybe
followed your advice and i created a generic fetch function
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-b0abc765a3b7c7158a09dc4d11771c0cc58bf9a6d6f158c2791d2ad656fbb37fR4-R19

2021-07-21 14:52 UTC, CatalinB7 commented on dogs_labeling/frontend/src/models.ts
> +export interface myResponse {
done
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-ba7c7caf9a12bff712e797fb6a07161fcdb3706738bfb18fbb62b24aacdf202fR1-R11

2021-07-21 14:53 UTC, CatalinB7 commented on dogs_labeling/frontend/src/picsManipulation.ts
> +export function myClosure(idx: number) {
renamed it ```export function savePic(idx: number)```

2021-07-21 14:57 UTC, CatalinB7 commented on dogs_labeling/frontend/src/picsManipulation.ts
> +        if (alreadySent[text][idx]) {
disabling button after it got clicked:
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-5835e833b0368ccea5f129aae6a43784e4c574154f58b8b560bd84d3ceb26ccaR13-R17

I keep the state of pictures on FE, but the backend also checks weather or not the request is valid.

2021-07-21 14:59 UTC, CatalinB7 commented on dogs_labeling/frontend/src/picsManipulation.ts
> +        let text = document.querySelector("h1").innerHTML;
Routes:
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-3cb787b8ed440dcf7e44c103d614a482c34866350f31e8b770afc564cab9225cR8-R23

Now checking the route in order to know what do display.

2021-07-21 15:00 UTC, CatalinB7 commented on dogs_labeling/frontend/index.html
> +    <script src="./dist/bundle.js"></script>
moved them
https://github.com/CatalinB7/dogs-labeling/pull/2/files#diff-4a3cfa61237c77c4d40e8b3f8324d29c6b86966ff024895baa9728ba0c45ccefR10-R12

2021-07-22 08:06 UTC, CatalinB7 commented on dogs_labeling/script.js
> +const noPics = 8;
done

2023-03-03 21:38 UTC, closed without merging